/* eslint-disable no-unused-vars */
const exbrowser = "firefox";
// values: "chrome", "safari", "edge", "firefox", "opera", "yandex", "whale"
const linkredirectionoptions = "https://www.turnoffthelights.com/browser/extension/options/";
const linkcapturescreenshot = "https://www.turnoffthelights.com/browser/extension/capture-screenshot-of-video/";
const linkdeveloperwebsite = "https://www.turnoffthelights.com";
const linkproduct = "https://addons.mozilla.org/firefox/addon/turn-off-the-lights";
const linkdonate = "https://www.turnoffthelights.com/donate/";
const writereview = "https://addons.mozilla.org/en-US/firefox/addon/turn-off-the-lights/reviews/";
const linkchangelog = "https://www.turnoffthelights.com/browser/extension/changelog/firefox/";
const linktranslate = "https://www.turnoffthelights.com/browser/extension/translate/";
const linksupport = "https://www.turnoffthelights.com/support/";
const linkwelcome = "https://www.turnoffthelights.com/browser/extension/welcome/firefox/";
const linkuninstall = "https://www.turnoffthelights.com/browser/extension/uninstall/firefox/";
const linkguide = "https://www.turnoffthelights.com/browser/extension/guide/firefox/";
const linkbrowsertheme = "https://www.turnoffthelights.com/browser/theme/";
const browsernewtab = "null";
const browserstore = "https://addons.mozilla.org";
const linkyoutube = "https://www.youtube.com/c/turnoffthelights?sub_confirmation=1";
const linkauroraplayerapp = "https://www.stefanvd.net/project/aurora-player/";
const linktotlmobileapp = "https://www.turnoffthelights.com/mobile/";
const linkgamepad = "https://www.turnoffthelights.com/game-controller/";
const devmode = true;
const devdonate = false;